# Generated by Django 3.1.2 on 2020-10-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Squirrel',
            new_name='SquirrelDetail',
        ),
    ]
