# Generated by Django 3.1.2 on 2020-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20201015_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=20, help_text='Latitude of Squirrel', max_digits=100)),
                ('Longtitude', models.DecimalField(decimal_places=20, help_text='Longitude of Squirrel', max_digits=100)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique ID of Squirrel', max_length=15)),
                ('Age', models.CharField(help_text='Age of Squirrel', max_length=15)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift of Sighting', max_length=5)),
                ('Date', models.DateField(help_text='Date of Sighting')),
                ('Squirrel_Image', models.ImageField(blank=True, help_text='Image of Squirrel', upload_to='Profiles_Images')),
            ],
        ),
        migrations.DeleteModel(
            name='SquirrelDetail',
        ),
    ]
